apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: nginx-tls
  namespace: cert-manager
spec:
  secretName: nginxtls
  issuerRef:
    name: letsencrypt-staging
  dnsNames:
  - '*.kavya.website'
  dns01:
        route53:
          region: us-east-1
          accessKeyID: AKIASMD4S7JQMU3USPXV
          secretAccessKeySecretRef:
            name: acme-route53
            key: secret-access-key
  
